apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sysdig-agent-xxl
  labels:
    tier: monitoring
    app: sysdig-agent-xxl
    version: v1
spec:
  template:
    metadata:
      labels:
        name: sysdig
    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #  app: sysdig
      hostPID: true
      hostIPC: true
      hostNetwork: false
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          env:
            - name: ZA_Server
              value: "zabbix-server"
            - name: ZA_ServerActive
              value: "zabbix-server"
          image: monitoringartist/dockbix-agent-xxl-limited
          # image: sysdig/sysdig
          name: sysdig
          volumeMounts:
            # - name: sysdig-scap-storage
            #   mountPath: /var/sysdig
            # - mountPath: /host/var/run/docker.sock
            #   name: docker-sock
            #   readOnly: false
            # - mountPath: /host/dev
            #   name: dev-vol
            #   readOnly: false
            # - mountPath: /host/proc
            #   name: proc-vol
            #   readOnly: true
            # - mountPath: /host/boot
            #   name: boot-vol
            #   readOnly: true
            # - mountPath: /host/lib/modules
            #   name: modules-vol
            #   readOnly: true
            # - mountPath: /host/usr
            #   name: usr-vol
            #   readOnly: true
            # - mountPath: /dev/shm
            #   name: dshm
            - name: rootfs
              mountPath: /rootfs
            - name: run
              mountPath: /var/run/
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: sysdig-scap-storage
          persistentVolumeClaim:
            claimName: sysdig-scap-storage-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: dev-vol
          hostPath:
            path: /dev
        - name: proc-vol
          hostPath:
            path: /proc
        - name: boot-vol
          hostPath:
            path: /boot
        - name: modules-vol
          hostPath:
            path: /lib/modules
        - name: usr-vol
          hostPath:
            path: /usr
        - name: rootfs
          hostPath:
              path: /
        - name: run
          hostPath:
              path: /var/run/
