kind: Service
apiVersion: v1
metadata:
  name: sftp
  labels:
    environment: production
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    app: sftp
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sftp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
        - name: sysdig-scap-storage
          persistentVolumeClaim:
            claimName: sysdig-scap-storage-pvc
      containers:
      - name: sftp
        image: atmoz/sftp
        imagePullPolicy: Always
        args:
        - foo:pass:1001;
        ports:
        - containerPort: 22
        volumeMounts:
          - name: sysdig-scap-storage
            mountPath: /home/foo/sysdig
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
